<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\Player;
use App\Models\Subscription;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class PlayerSeeder extends Seeder
{
    public function run(): void
    {
        $playersData = [
            [
                'first_name' => 'Léo',
                'last_name' => 'Dubois',
                'email' => 'leo.dubois@example.com',
                'position' => 'Milieu offensif',
                'level' => 'U19 National',
                'nationality' => 'Français',
                'dominant_foot' => 'Droit',
                'height_cm' => 178,
                'weight_kg' => 70,
                'current_club' => 'Auxerre Academy',
                'bio' => 'Milieu offensif doté d\'une excellente vision du jeu et d\'une grande qualité de passe. Formé au club, travailleur et à l\'écoute.',
                'main_video_url' => 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'radar_mental' => 88,
                'radar_physique' => 74,
                'radar_technique' => 90,
                'radar_vitesse' => 82,
                'radar_vision' => 92,
                'radar_social' => 85,
                'is_premium' => true,
            ],
            [
                'first_name' => 'Lucas',
                'last_name' => 'Hernandez',
                'email' => 'lucas.hernandez@example.com',
                'position' => 'Défenseur central',
                'level' => 'National 3',
                'nationality' => 'Français',
                'dominant_foot' => 'Gauche',
                'height_cm' => 186,
                'weight_kg' => 80,
                'current_club' => 'Sans club',
                'bio' => 'Défenseur physique, rigoureux dans les duels aériens et au sol. Très fort tempérament de gagnant.',
                'main_video_url' => 'https://www.youtube.com/watch?v=48nJg1c5Z0k',
                'radar_mental' => 92,
                'radar_physique' => 88,
                'radar_technique' => 72,
                'radar_vitesse' => 78,
                'radar_vision' => 70,
                'radar_social' => 80,
                'is_premium' => false,
            ],
            [
                'first_name' => 'Amadou',
                'last_name' => 'Sow',
                'email' => 'amadou.sow@example.com',
                'position' => 'Buteur',
                'level' => 'U17 National',
                'nationality' => 'Sénégalais',
                'dominant_foot' => 'Droit',
                'height_cm' => 184,
                'weight_kg' => 76,
                'current_club' => 'PSG Academy',
                'bio' => 'Attaquant puissant, finisseur clinique des deux pieds. Très bonne capacité d\'appel dans le dos de la défense.',
                'main_video_url' => 'https://www.youtube.com/watch?v=mDGB8Yk12gA',
                'radar_mental' => 82,
                'radar_physique' => 85,
                'radar_technique' => 80,
                'radar_vitesse' => 91,
                'radar_vision' => 75,
                'radar_social' => 78,
                'is_premium' => true,
            ],
            [
                'first_name' => 'Mateo',
                'last_name' => 'Silva',
                'email' => 'mateo.silva@example.com',
                'position' => 'Ailier gauche',
                'level' => 'U19 National',
                'nationality' => 'Portugais',
                'dominant_foot' => 'Droit',
                'height_cm' => 174,
                'weight_kg' => 68,
                'current_club' => 'AS Monaco',
                'bio' => 'Ailier très technique et percutant. Aime repiquer au centre pour frapper. Très agile dans les petits espaces.',
                'main_video_url' => null,
                'radar_mental' => 75,
                'radar_physique' => 70,
                'radar_technique' => 92,
                'radar_vitesse' => 89,
                'radar_vision' => 80,
                'radar_social' => 82,
                'is_premium' => false,
            ],
            [
                'first_name' => 'Enzo',
                'last_name' => 'Ferrara',
                'email' => 'enzo.ferrara@example.com',
                'position' => 'Milieu défensif',
                'level' => 'National 2',
                'nationality' => 'Italien',
                'dominant_foot' => 'Droit',
                'height_cm' => 180,
                'weight_kg' => 75,
                'current_club' => 'Le Havre AC',
                'bio' => 'Milieu défensif infatigable, excellent à la récupération et premier relanceur propre. Leader vocal sur le terrain.',
                'main_video_url' => 'https://www.youtube.com/watch?v=k77G4G1W1Xg',
                'radar_mental' => 95,
                'radar_physique' => 84,
                'radar_technique' => 78,
                'radar_vitesse' => 72,
                'radar_vision' => 85,
                'radar_social' => 90,
                'is_premium' => true,
            ],
            [
                'first_name' => 'Sofiane',
                'last_name' => 'Bouazza',
                'email' => 'sofiane.bouazza@example.com',
                'position' => 'Ailier droit',
                'level' => 'U19 National',
                'nationality' => 'Algérien',
                'dominant_foot' => 'Gauche',
                'height_cm' => 172,
                'weight_kg' => 65,
                'current_club' => 'Toulouse FC',
                'bio' => 'Piston ou ailier droit ultra rapide. Très bon centreur en course. Gros volume de jeu défensif et offensif.',
                'main_video_url' => null,
                'radar_mental' => 78,
                'radar_physique' => 80,
                'radar_technique' => 83,
                'radar_vitesse' => 94,
                'radar_vision' => 74,
                'radar_social' => 80,
                'is_premium' => false,
            ],
            [
                'first_name' => 'Marc',
                'last_name' => 'Lefevre',
                'email' => 'marc.lefevre@example.com',
                'position' => 'Gardien',
                'level' => 'National 3',
                'nationality' => 'Belge',
                'dominant_foot' => 'Gauche',
                'height_cm' => 192,
                'weight_kg' => 85,
                'current_club' => 'Standard de Liège',
                'bio' => 'Gardien imposant, impérial sur sa ligne et rassurant dans les sorties aériennes. Très bon jeu au pied long.',
                'main_video_url' => 'https://www.youtube.com/watch?v=f0b2fB5K-8g',
                'radar_mental' => 88,
                'radar_physique' => 82,
                'radar_technique' => 76,
                'radar_vitesse' => 70,
                'radar_vision' => 80,
                'radar_social' => 85,
                'is_premium' => true,
            ],
            [
                'first_name' => 'Ismaël',
                'last_name' => 'Koffi',
                'email' => 'ismael.koffi@example.com',
                'position' => 'Latéral gauche',
                'level' => 'U17 National',
                'nationality' => 'Ivoirien',
                'dominant_foot' => 'Gauche',
                'height_cm' => 176,
                'weight_kg' => 71,
                'current_club' => 'Rennes Academy',
                'bio' => 'Latéral moderne doté d\'une superbe endurance. Apporte constamment le surnombre offensivement et solide défensivement.',
                'main_video_url' => null,
                'radar_mental' => 80,
                'radar_physique' => 90,
                'radar_technique' => 81,
                'radar_vitesse' => 87,
                'radar_vision' => 76,
                'radar_social' => 82,
                'is_premium' => false,
            ],
            [
                'first_name' => 'Arthur',
                'last_name' => 'Moreau',
                'email' => 'arthur.moreau@example.com',
                'position' => 'Milieu central',
                'level' => 'U19 National',
                'nationality' => 'Français',
                'dominant_foot' => 'Ambidextre',
                'height_cm' => 182,
                'weight_kg' => 77,
                'current_club' => 'Sans club',
                'bio' => 'Milieu "box-to-box" avec un coffre physique impressionnant. Capable de récupérer et de se projeter rapidement dans la surface adverse.',
                'main_video_url' => 'https://www.youtube.com/watch?v=e8R-H1K8m7o',
                'radar_mental' => 85,
                'radar_physique' => 92,
                'radar_technique' => 80,
                'radar_vitesse' => 80,
                'radar_vision' => 82,
                'radar_social' => 78,
                'is_premium' => false,
            ],
            [
                'first_name' => 'Karim',
                'last_name' => 'Benziane',
                'email' => 'karim.benz@example.com',
                'position' => 'Buteur',
                'level' => 'National 3',
                'nationality' => 'Marocain',
                'dominant_foot' => 'Droit',
                'height_cm' => 185,
                'weight_kg' => 78,
                'current_club' => 'Montpellier HSC',
                'bio' => 'Renard des surfaces redoutable, très fort dos au jeu. Jeu de tête exceptionnel et grand sens du placement.',
                'main_video_url' => 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'radar_mental' => 89,
                'radar_physique' => 81,
                'radar_technique' => 82,
                'radar_vitesse' => 78,
                'radar_vision' => 79,
                'radar_social' => 80,
                'is_premium' => true,
            ],
            [
                'first_name' => 'Yanis',
                'last_name' => 'Boucher',
                'email' => 'yanis.boucher@example.com',
                'position' => 'Latéral droit',
                'level' => 'U19 National',
                'nationality' => 'Français',
                'dominant_foot' => 'Droit',
                'height_cm' => 177,
                'weight_kg' => 72,
                'current_club' => 'Metz Academy',
                'bio' => 'Latéral dynamique et appliqué tactiquement. Très bonne capacité d\'interception et de relance rapide.',
                'main_video_url' => null,
                'radar_mental' => 83,
                'radar_physique' => 82,
                'radar_technique' => 75,
                'radar_vitesse' => 85,
                'radar_vision' => 71,
                'radar_social' => 84,
                'is_premium' => false,
            ],
            [
                'first_name' => 'Bastien',
                'last_name' => 'Girard',
                'email' => 'bastien.girard@example.com',
                'position' => 'Défenseur central',
                'level' => 'National 2',
                'nationality' => 'Français',
                'dominant_foot' => 'Droit',
                'height_cm' => 189,
                'weight_kg' => 83,
                'current_club' => 'Nancy',
                'bio' => 'Défenseur central moderne, calme sous pression avec une relance de balle très précise longue et courte.',
                'main_video_url' => 'https://www.youtube.com/watch?v=48nJg1c5Z0k',
                'radar_mental' => 90,
                'radar_physique' => 85,
                'radar_technique' => 81,
                'radar_vitesse' => 74,
                'radar_vision' => 83,
                'radar_social' => 88,
                'is_premium' => true,
            ],
            [
                'first_name' => 'Diego',
                'last_name' => 'Gomez',
                'email' => 'diego.gomez@example.com',
                'position' => 'Milieu offensif',
                'level' => 'U19 National',
                'nationality' => 'Espagnol',
                'dominant_foot' => 'Gauche',
                'height_cm' => 171,
                'weight_kg' => 64,
                'current_club' => 'Nice Academy',
                'bio' => 'N°10 à l\'ancienne, une technique soyeuse et une créativité hors pair pour débloquer les blocs bas défensifs.',
                'main_video_url' => null,
                'radar_mental' => 78,
                'radar_physique' => 65,
                'radar_technique' => 95,
                'radar_vitesse' => 80,
                'radar_vision' => 94,
                'radar_social' => 86,
                'is_premium' => false,
            ],
            [
                'first_name' => 'Samuel',
                'last_name' => 'Eto',
                'email' => 'samuel.eto@example.com',
                'position' => 'Buteur',
                'level' => 'U17 National',
                'nationality' => 'Camerounais',
                'dominant_foot' => 'Droit',
                'height_cm' => 179,
                'weight_kg' => 73,
                'current_club' => 'Lille OSC',
                'bio' => 'Attaquant percutant avec une incroyable accélération. Très intelligent dans ses courses sans ballon et pressing.',
                'main_video_url' => 'https://www.youtube.com/watch?v=mDGB8Yk12gA',
                'radar_mental' => 84,
                'radar_physique' => 81,
                'radar_technique' => 84,
                'radar_vitesse' => 93,
                'radar_vision' => 76,
                'radar_social' => 82,
                'is_premium' => true,
            ],
            [
                'first_name' => 'Mathis',
                'last_name' => 'Gauthier',
                'email' => 'mathis.gauthier@example.com',
                'position' => 'Gardien',
                'level' => 'U19 National',
                'nationality' => 'Français',
                'dominant_foot' => 'Droit',
                'height_cm' => 188,
                'weight_kg' => 81,
                'current_club' => 'Sans club',
                'bio' => 'Très agile sur sa ligne avec d\'excellents réflexes sur les frappes à mi-distance. Tempérament calme et concentré.',
                'main_video_url' => null,
                'radar_mental' => 85,
                'radar_physique' => 79,
                'radar_technique' => 74,
                'radar_vitesse' => 78,
                'radar_vision' => 72,
                'radar_social' => 80,
                'is_premium' => false,
            ],
            [
                'first_name' => 'Hugo',
                'last_name' => 'Rousseau',
                'email' => 'hugo.rousseau@example.com',
                'position' => 'Milieu central',
                'level' => 'National 3',
                'nationality' => 'Français',
                'dominant_foot' => 'Droit',
                'height_cm' => 181,
                'weight_kg' => 76,
                'current_club' => 'Nantes',
                'bio' => 'Milieu de terrain polyvalent et très propre techniquement. Assure la fluidité du jeu avec un taux de passes réussies élevé.',
                'main_video_url' => null,
                'radar_mental' => 87,
                'radar_physique' => 80,
                'radar_technique' => 85,
                'radar_vitesse' => 76,
                'radar_vision' => 84,
                'radar_social' => 89,
                'is_premium' => false,
            ],
            [
                'first_name' => 'William',
                'last_name' => 'Mendy',
                'email' => 'william.mendy@example.com',
                'position' => 'Défenseur central',
                'level' => 'U19 National',
                'nationality' => 'Sénégalais',
                'dominant_foot' => 'Droit',
                'height_cm' => 191,
                'weight_kg' => 86,
                'current_club' => 'Saint-Étienne',
                'bio' => 'Défenseur athlétique et puissant. Très fort dans le marquage individuel et les tacles glissés de dernier recours.',
                'main_video_url' => 'https://www.youtube.com/watch?v=k77G4G1W1Xg',
                'radar_mental' => 86,
                'radar_physique' => 93,
                'radar_technique' => 70,
                'radar_vitesse' => 81,
                'radar_vision' => 68,
                'radar_social' => 82,
                'is_premium' => false,
            ],
            [
                'first_name' => 'Thomas',
                'last_name' => 'Petit',
                'email' => 'thomas.petit@example.com',
                'position' => 'Ailier gauche',
                'level' => 'U17 National',
                'nationality' => 'Français',
                'dominant_foot' => 'Gauche',
                'height_cm' => 173,
                'weight_kg' => 67,
                'current_club' => 'Sans club',
                'bio' => 'Ailier provocateur, rapide et explosif dans les 20 derniers mètres. Bon passeur décisif pour les attaquants.',
                'main_video_url' => null,
                'radar_mental' => 74,
                'radar_physique' => 72,
                'radar_technique' => 89,
                'radar_vitesse' => 92,
                'radar_vision' => 78,
                'radar_social' => 76,
                'is_premium' => false,
            ],
            [
                'first_name' => 'Bilal',
                'last_name' => 'Fakir',
                'email' => 'bilal.fakir@example.com',
                'position' => 'Milieu central',
                'level' => 'National 3',
                'nationality' => 'Marocain',
                'dominant_foot' => 'Ambidextre',
                'height_cm' => 180,
                'weight_kg' => 74,
                'current_club' => 'Strasbourg',
                'bio' => 'Milieu relayeur technique, très intelligent tactiquement. Capable de dicter le rythme d\'un match à lui seul.',
                'main_video_url' => 'https://www.youtube.com/watch?v=f0b2fB5K-8g',
                'radar_mental' => 91,
                'radar_physique' => 78,
                'radar_technique' => 88,
                'radar_vitesse' => 75,
                'radar_vision' => 90,
                'radar_social' => 87,
                'is_premium' => true,
            ],
            [
                'first_name' => 'Nicolas',
                'last_name' => 'Vincent',
                'email' => 'nicolas.vincent@example.com',
                'position' => 'Buteur',
                'level' => 'U19 National',
                'nationality' => 'Français',
                'dominant_foot' => 'Droit',
                'height_cm' => 183,
                'weight_kg' => 77,
                'current_club' => 'Reims Academy',
                'bio' => 'Attaquant rapide et combatif, effectue de nombreuses courses pour l\'équipe. Excellente efficacité face au but.',
                'main_video_url' => null,
                'radar_mental' => 82,
                'radar_physique' => 84,
                'radar_technique' => 80,
                'radar_vitesse' => 87,
                'radar_vision' => 73,
                'radar_social' => 85,
                'is_premium' => false,
            ]
        ];

        foreach ($playersData as $index => $data) {
            $user = User::where('email', $data['email'])->first();
            if (!$user) {
                $user = User::create([
                    'name' => str_replace(' ', '_', strtolower($data['first_name'] . ' ' . $data['last_name'])),
                    'email' => $data['email'],
                    'password' => Hash::make('password123'),
                    'role' => 'player',
                    'email_verified_at' => now(),
                ]);
            }
            $videoUrl = $data['main_video_url'];
            if ($videoUrl) {
                if ($index % 3 === 0) {
                    $videoUrl = '/videos/ilian.mp4';
                } elseif ($index % 3 === 1) {
                    $videoUrl = '/videos/header.mp4';
                } else {
                    $videoUrl = '/videos/Nutrition_pour_Footballeurs.mp4';
                }
            }

            $player = Player::updateOrCreate(
                ['user_id' => $user->id],
                [
                    'first_name' => $data['first_name'],
                    'last_name' => $data['last_name'],
                    'date_of_birth' => now()->subYears(rand(16, 22))->subMonths(rand(1, 11))->subDays(rand(1, 28))->format('Y-m-d'),
                    'nationality' => $data['nationality'],
                    'position' => $data['position'],
                    'dominant_foot' => $data['dominant_foot'],
                    'height_cm' => $data['height_cm'],
                    'weight_kg' => $data['weight_kg'],
                    'current_club' => $data['current_club'],
                    'contract_until' => now()->addYears(rand(1, 3))->format('Y-m-d'),
                    'market_value' => rand(5000, 150000),
                    'visibility' => 'public',
                    'bio' => $data['bio'],
                    'phone' => '+33 6 ' . rand(10, 99) . ' ' . rand(10, 99) . ' ' . rand(10, 99) . ' ' . rand(10, 99),
                    'level' => $data['level'],
                    'main_video_url' => $videoUrl,
                    'profile_photo' => 'profile_photos/' . ($index + 1) . '.jpg',
                    'profile_completed' => true,
                    'jersey_number' => rand(1, 99),
                    'radar_mental' => $data['radar_mental'],
                    'radar_physique' => $data['radar_physique'],
                    'radar_technique' => $data['radar_technique'],
                    'radar_vitesse' => $data['radar_vitesse'],
                    'radar_vision' => $data['radar_vision'],
                    'radar_social' => $data['radar_social'],
                    'matches_played' => rand(10, 30),
                    'goals_scored' => in_array($data['position'], ['Buteur', 'Ailier gauche', 'Ailier droit']) ? rand(8, 22) : rand(0, 5),
                    'assists' => in_array($data['position'], ['Milieu offensif', 'Ailier gauche', 'Ailier droit']) ? rand(6, 18) : rand(0, 4),
                    'season' => '2025/2026',
                ]
            );

            if ($data['is_premium']) {
                Subscription::updateOrCreate(
                    ['user_id' => $user->id, 'plan_name' => 'PREMIUM'],
                    [
                        'status' => 'active',
                        'ends_at' => now()->addMonths(6),
                    ]
                );
            } else {
                // If it is standard, let's make sure it doesn't have an active premium subscription
                Subscription::where('user_id', $user->id)->where('plan_name', 'PREMIUM')->delete();
            }
        }
    }
}
